export const theme = {
    colors: {
        primary: '#FF4B4B',
        secondary: '#2D2D2D',
        accent: {
            red: '#FF4B4B',
            orange: '#FF8F00',
            yellow: '#FFD600',
            green: '#00C853',
            blue: '#2196F3',
            purple: '#7C4DFF',
        },
        background: {
            primary: '#121212',
            secondary: '#1E1E1E',
            tertiary: '#252525',
            overlay: 'rgba(0, 0, 0, 0.8)',
        },
        text: {
            primary: '#FFFFFF',
            secondary: '#B3B3B3',
            accent: '#808080',
        },
        border: '#333333',
        error: '#FF4B4B',
        success: '#00C853',
        warning: '#FF8F00',
    },
    spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
    },
    borderRadius: {
        sm: '4px',
        md: '6px',
        lg: '8px',
        xl: '12px',
        full: '9999px',
    },
    shadows: {
        sm: '0 2px 4px rgba(0, 0, 0, 0.2)',
        md: '0 4px 8px rgba(0, 0, 0, 0.3)',
        lg: '0 8px 16px rgba(0, 0, 0, 0.4)',
        xl: '0 12px 24px rgba(0, 0, 0, 0.5)',
        highlight: '0 0 0 1px rgba(255, 75, 75, 0.3)',
    },
    transitions: {
        fast: 'all 0.15s cubic-bezier(0.4, 0, 0.2, 1)',
        normal: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
        slow: 'all 0.5s cubic-bezier(0.4, 0, 0.2, 1)',
    },
    fonts: {
        heading: '"SF Pro Display", -apple-system, BlinkMacSystemFont, sans-serif',
        body: '"SF Pro Text", -apple-system, BlinkMacSystemFont, sans-serif',
        mono: '"SF Mono", "Fira Code", monospace',
    },
    fontSizes: {
        xs: '11px',
        sm: '13px',
        md: '14px',
        lg: '16px',
        xl: '18px',
        '2xl': '20px',
        '3xl': '24px',
    },
    componentColors: {
        text: '#2196F3',
        title: '#7C4DFF',
        voice: '#FF4B4B',
        comparison: '#00C853',
        countdown: '#FF8F00',
        transition: '#FFD600',
    },
}; 